# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
cache:
 directories:
   - /Library/Ruby/Gems/2.0.0
   - ~/Library/Caches/CocoaPods
   - ~/.cocoapods
   - Example/Pods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $(xcrun instruments -s | grep -o "iPhone 6 \(.*\) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/" | awk '{print $1;}')
- set -o pipefail 
- xcodebuild build -workspace Example/ABCropRotateView.xcworkspace -scheme ABCropRotateView-Example -sdk iphonesimulator -destination "OS=9.2,name=iPhone 6" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
#- xcodebuild test -workspace Example/ABCropRotateView.xcworkspace -scheme ABCropRotateView-Example -sdk iphonesimulator -destination "OS=9.2,name=iPhone 6" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
- pod lib lint
